/**
 * npm run schedule: rebuild content/schedule.json from the riddle pool (see lib/scheduleBuilder.ts).
 *
 *   npm run schedule                                  # from LAUNCH_DATE, 365 days, keeps days up to today
 *   npm run schedule -- --start 2026-11-01 --days 400
 *   npm run schedule -- --rebuild                     # pre-launch only: redo every day, today included
 *   npm run schedule -- --dry-run                     # print stats, don't write
 *
 * Published days (today and earlier, America/Toronto) are never changed unless --rebuild is passed.
 */
import fs from 'node:fs';
import path from 'node:path';
import { config } from 'dotenv';

config({ path: '.env.local', quiet: true });
config({ quiet: true });

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

async function main() {
  const { loadContent, contentDir } = await import('../lib/contentLoader');
  const { validateRiddle, validateSchedule, REPEAT_GAP_DAYS } = await import('../lib/content');
  const { buildSchedule } = await import('../lib/scheduleBuilder');
  const { addDays, todayPuzzleDate, launchDate } = await import('../lib/dates');

  const content = loadContent();
  const bad = content.riddles.filter(({ riddle, fileId }) => validateRiddle(riddle, { simIds: content.simIds, fileId }).length);
  if (bad.length) {
    console.error(`✗ Fix these riddles first (npm run seed -- --check): ${bad.map((b) => b.fileId).join(', ')}`);
    process.exit(1);
  }
  const riddles = content.riddles.map((r) => r.riddle);
  const existing = content.schedule;
  const start = arg('start') ?? launchDate();
  const days = Number(arg('days') ?? 365);
  const tomorrow = addDays(todayPuzzleDate(), 1);
  const keepBefore = process.argv.includes('--rebuild') || start >= tomorrow ? undefined : tomorrow;

  const { schedule, pools, minGap, repeatedTrios } = buildSchedule(riddles, { start, days, existing, keepBefore });
  const errors = validateSchedule(schedule, new Map(riddles.map((r) => [r.id, r])));
  if (errors.length) {
    console.error(`✗ Built schedule is invalid:\n  ${errors.slice(0, 10).join('\n  ')}`);
    process.exit(1);
  }

  const last = addDays(start, days - 1);
  console.log(`Pools: warm-up ${pools.warmup}, trap ${pools.trap}, boss ${pools.boss} (repeat gap ${REPEAT_GAP_DAYS} days)`);
  console.log(`Days: ${start} → ${last} (${days})${keepBefore ? `, kept as they were before ${keepBefore}` : ''}`);
  console.log(`${minGap === null ? 'No riddle repeats' : `Shortest gap before a riddle returns: ${minGap} days`}; repeated trios: ${repeatedTrios}`);
  if (process.argv.includes('--dry-run')) return;

  const out: Record<string, unknown> = {
    _comment: `puzzle_date (America/Toronto) -> riddle ids per slot. Generated by \`npm run schedule\` (lib/scheduleBuilder.ts): each tier rotates through its pool, a riddle returns after at least ${REPEAT_GAP_DAYS} days, and the trap slot is always a number riddle. Edit riddles, then rerun; published days are kept.`,
    ...schedule,
  };
  fs.writeFileSync(path.join(contentDir(), 'schedule.json'), JSON.stringify(out, null, 2) + '\n');
  console.log(`✓ Wrote content/schedule.json`);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
